package com.prototype.smartlayout.model.enums;

public enum ComponentDimensionEnum {
	TINY_TINY(SizeEnum.TINY, SizeEnum.TINY),
	TINY_SMALLER(SizeEnum.TINY, SizeEnum.SMALLER),
	TINY_SMALL(SizeEnum.TINY, SizeEnum.SMALL),
	TINY_SMALL_SLACK(SizeEnum.TINY, SizeEnum.SMALL_SLACK),
	TINY_MEDIUM(SizeEnum.TINY, SizeEnum.MEDIUM),
	TINY_LARGE_SLACK(SizeEnum.TINY, SizeEnum.LARGE_SLACK),
	TINY_LARGE(SizeEnum.TINY, SizeEnum.LARGE),
	TINY_LARGER(SizeEnum.TINY, SizeEnum.LARGER),
	TINY_HUGE(SizeEnum.TINY, SizeEnum.HUGE),
	TINY_GIGANTIC(SizeEnum.TINY, SizeEnum.GIGANTIC),

	SMALLER_TINY(SizeEnum.SMALLER, SizeEnum.TINY),
	SMALLER_SMALLER(SizeEnum.SMALLER, SizeEnum.SMALLER),
	SMALLER_SMALL(SizeEnum.SMALLER, SizeEnum.SMALL),
	SMALLER_SMALL_SLACK(SizeEnum.SMALLER, SizeEnum.SMALL_SLACK),
	SMALLER_MEDIUM(SizeEnum.SMALLER, SizeEnum.MEDIUM),
	SMALLER_LARGE_SLACK(SizeEnum.SMALLER, SizeEnum.LARGE_SLACK),
	SMALLER_LARGE(SizeEnum.SMALLER, SizeEnum.LARGE),
	SMALLER_LARGER(SizeEnum.SMALLER, SizeEnum.LARGER),
	SMALLER_HUGE(SizeEnum.SMALLER, SizeEnum.HUGE),
	SMALLER_GIGANTIC(SizeEnum.SMALLER, SizeEnum.GIGANTIC),

	SMALL_TINY(SizeEnum.SMALL, SizeEnum.TINY),
	SMALL_SMALLER(SizeEnum.SMALL, SizeEnum.SMALLER),
	SMALL_SMALL(SizeEnum.SMALL, SizeEnum.SMALL),
	SMALL_SMALL_SLACK(SizeEnum.SMALL, SizeEnum.SMALL_SLACK),
	SMALL_MEDIUM(SizeEnum.SMALL, SizeEnum.MEDIUM),
	SMALL_LARGE_SLACK(SizeEnum.SMALL, SizeEnum.LARGE_SLACK),
	SMALL_LARGE(SizeEnum.SMALL, SizeEnum.LARGE),
	SMALL_LARGER(SizeEnum.SMALL, SizeEnum.LARGER),
	SMALL_HUGE(SizeEnum.SMALL, SizeEnum.HUGE),
	SMALL_GIGANTIC(SizeEnum.SMALL, SizeEnum.GIGANTIC),

	SMALL_SLACK_TINY(SizeEnum.SMALL_SLACK, SizeEnum.TINY),
	SMALL_SLACK_SMALLER(SizeEnum.SMALL_SLACK, SizeEnum.SMALLER),
	SMALL_SLACK_SMALL(SizeEnum.SMALL_SLACK, SizeEnum.SMALL),
	SMALL_SLACK_SMALL_SLACK(SizeEnum.SMALL_SLACK, SizeEnum.SMALL_SLACK),
	SMALL_SLACK_MEDIUM(SizeEnum.SMALL_SLACK, SizeEnum.MEDIUM),
	SMALL_SLACK_LARGE_SLACK(SizeEnum.SMALL_SLACK, SizeEnum.LARGE_SLACK),
	SMALL_SLACK_LARGE(SizeEnum.SMALL_SLACK, SizeEnum.LARGE),
	SMALL_SLACK_LARGER(SizeEnum.SMALL_SLACK, SizeEnum.LARGER),
	SMALL_SLACK_HUGE(SizeEnum.SMALL_SLACK, SizeEnum.HUGE),
	SMALL_SLACK_GIGANTIC(SizeEnum.SMALL_SLACK, SizeEnum.GIGANTIC),

	MEDIUM_TINY(SizeEnum.MEDIUM, SizeEnum.TINY),
	MEDIUM_SMALLER(SizeEnum.MEDIUM, SizeEnum.SMALLER),
	MEDIUM_SMALL(SizeEnum.MEDIUM, SizeEnum.SMALL),
	MEDIUM_SMALL_SLACK(SizeEnum.MEDIUM, SizeEnum.SMALL_SLACK),
	MEDIUM_MEDIUM(SizeEnum.MEDIUM, SizeEnum.MEDIUM),
	MEDIUM_LARGE_SLACK(SizeEnum.MEDIUM, SizeEnum.LARGE_SLACK),
	MEDIUM_LARGE(SizeEnum.MEDIUM, SizeEnum.LARGE),
	MEDIUM_LARGER(SizeEnum.MEDIUM, SizeEnum.LARGER),
	MEDIUM_HUGE(SizeEnum.MEDIUM, SizeEnum.HUGE),
	MEDIUM_GIGANTIC(SizeEnum.MEDIUM, SizeEnum.GIGANTIC),

	LARGE_SLACK_TINY(SizeEnum.LARGE_SLACK, SizeEnum.TINY),
	LARGE_SLACK_SMALLER(SizeEnum.LARGE_SLACK, SizeEnum.SMALLER),
	LARGE_SLACK_SMALL(SizeEnum.LARGE_SLACK, SizeEnum.SMALL),
	LARGE_SLACK_SMALL_SLACK(SizeEnum.LARGE_SLACK, SizeEnum.SMALL_SLACK),
	LARGE_SLACK_MEDIUM(SizeEnum.LARGE_SLACK, SizeEnum.MEDIUM),
	LARGE_SLACK_LARGE_SLACK(SizeEnum.LARGE_SLACK, SizeEnum.LARGE_SLACK),
	LARGE_SLACK_LARGE(SizeEnum.LARGE_SLACK, SizeEnum.LARGE),
	LARGE_SLACK_LARGER(SizeEnum.LARGE_SLACK, SizeEnum.LARGER),
	LARGE_SLACK_HUGE(SizeEnum.LARGE_SLACK, SizeEnum.HUGE),
	LARGE_SLACK_GIGANTIC(SizeEnum.LARGE_SLACK, SizeEnum.GIGANTIC),

	LARGE_TINY(SizeEnum.LARGE, SizeEnum.TINY),
	LARGE_SMALLER(SizeEnum.LARGE, SizeEnum.SMALLER),
	LARGE_SMALL(SizeEnum.LARGE, SizeEnum.SMALL),
	LARGE_SMALL_SLACK(SizeEnum.LARGE, SizeEnum.SMALL_SLACK),
	LARGE_MEDIUM(SizeEnum.LARGE, SizeEnum.MEDIUM),
	LARGE_LARGE_SLACK(SizeEnum.LARGE, SizeEnum.LARGE_SLACK),
	LARGE_LARGE(SizeEnum.LARGE, SizeEnum.LARGE),
	LARGE_LARGER(SizeEnum.LARGE, SizeEnum.LARGER),
	LARGE_HUGE(SizeEnum.LARGE, SizeEnum.HUGE),
	LARGE_GIGANTIC(SizeEnum.LARGE, SizeEnum.GIGANTIC),

	LARGER_TINY(SizeEnum.LARGER, SizeEnum.TINY),
	LARGER_SMALLER(SizeEnum.LARGER, SizeEnum.SMALLER),
	LARGER_SMALL(SizeEnum.LARGER, SizeEnum.SMALL),
	LARGER_SMALL_SLACK(SizeEnum.LARGER, SizeEnum.SMALL_SLACK),
	LARGER_MEDIUM(SizeEnum.LARGER, SizeEnum.MEDIUM),
	LARGER_LARGE_SLACK(SizeEnum.LARGER, SizeEnum.LARGE_SLACK),
	LARGER_LARGE(SizeEnum.LARGER, SizeEnum.LARGE),
	LARGER_LARGER(SizeEnum.LARGER, SizeEnum.LARGER),
	LARGER_HUGE(SizeEnum.LARGER, SizeEnum.HUGE),
	LARGER_GIGANTIC(SizeEnum.LARGER, SizeEnum.GIGANTIC),

	HUGE_TINY(SizeEnum.HUGE, SizeEnum.TINY),
	HUGE_SMALLER(SizeEnum.HUGE, SizeEnum.SMALLER),
	HUGE_SMALL(SizeEnum.HUGE, SizeEnum.SMALL),
	HUGE_SMALL_SLACK(SizeEnum.HUGE, SizeEnum.SMALL_SLACK),
	HUGE_MEDIUM(SizeEnum.HUGE, SizeEnum.MEDIUM),
	HUGE_LARGE_SLACK(SizeEnum.HUGE, SizeEnum.LARGE_SLACK),
	HUGE_LARGE(SizeEnum.HUGE, SizeEnum.LARGE),
	HUGE_LARGER(SizeEnum.HUGE, SizeEnum.LARGER),
	HUGE_HUGE(SizeEnum.HUGE, SizeEnum.HUGE),
	HUGE_GIGANTIC(SizeEnum.HUGE, SizeEnum.GIGANTIC),

	GIGANTIC_TINY(SizeEnum.GIGANTIC, SizeEnum.TINY),
	GIGANTIC_SMALLER(SizeEnum.GIGANTIC, SizeEnum.SMALLER),
	GIGANTIC_SMALL(SizeEnum.GIGANTIC, SizeEnum.SMALL),
	GIGANTIC_SMALL_SLACK(SizeEnum.GIGANTIC, SizeEnum.SMALL_SLACK),
	GIGANTIC_MEDIUM(SizeEnum.GIGANTIC, SizeEnum.MEDIUM),
	GIGANTIC_LARGE_SLACK(SizeEnum.GIGANTIC, SizeEnum.LARGE_SLACK),
	GIGANTIC_LARGE(SizeEnum.GIGANTIC, SizeEnum.LARGE),
	GIGANTIC_LARGER(SizeEnum.GIGANTIC, SizeEnum.LARGER),
	GIGANTIC_HUGE(SizeEnum.GIGANTIC, SizeEnum.HUGE),
	GIGANTIC_GIGANTIC(SizeEnum.GIGANTIC, SizeEnum.GIGANTIC);

	public final int minWidth;
	public final int maxWidth;
	public final int minHeight;
	public final int maxHeight;

	ComponentDimensionEnum (SizeEnum width, SizeEnum height)
	{
		this.minWidth = width.min;
		this.maxWidth = width.max;
		this.minHeight = height.min;
		this.maxHeight = height.max;
	}
}
